### ISSUE TITLE
Evaluate.service on Silicon Mac

### ISSUE THREAD

**Issue by woncheol-kim** [DavidPhillipOster/evaluate_service#1]
Hi, I've been using this app for years and I thank you so much for your contribution!

I've recently bought an M1 Mac Mini, and noticed that this app runs via Rosetta.
So I've tried to build it again on my new M1 Mac and found that it still runs via Rosetta.

My question: is the source code indeed expected to run on a Intel Mac? Or did I make some mistakes?
Please note that I'm not actually a computer guy, and I know almost nothing about programming.

Thanks.

**Comment by DavidPhillipOster** [comment]
Thanks for bringing this to my attention.

**Comment by DavidPhillipOster** [comment]
ReadMe.md file fixed. Fat Binary uploaded as a .zip in a new release.

**Comment by woncheol-kim** [comment]
Thank you for the binary file. And Happy Holidays!
